In [1]:
import numpy as np

In [2]:
np.array( [1.0, 2, 3.5, 0.2, "True"] )

array(['1.0', '2', '3.5', '0.2', 'True'], dtype='<U32')

In [3]:
np.array( [1.0, 2, 3.5, 0.2, True] )

array([1. , 2. , 3.5, 0.2, 1. ])

In [4]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]

In [5]:
print(array_1[:3])

[1, 2, 3]


In [6]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[2:-3])

[3, 5, 4, 6, 7, 8]


In [7]:
array_1 = [1,2,3,5,4,6,7,8,5,3,2]
print(array_1[ : : -2])

[2, 5, 7, 4, 3, 1]


In [2]:
import numpy as np
n=int(input("Enter the size of array which you want: "))
a=np.zeros((n,n), dtype=int)
a=np.arange(n)==n//2
a=a*1|a[:,None]
print(a)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]
